version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: zillow_nz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_password
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # Backend API
  backend:
    image: ghcr.io/YOUR_ORG/zillow-agent-lead-gen-app/backend:latest
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:password@postgres:5432/zillow_nz
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3000
      API_URL: https://api.yourdomain.com
      CORS_ORIGIN: https://yourdomain.com
      STRIPE_SECRET_KEY_FILE: /run/secrets/stripe_secret_key
      RESEND_API_KEY_FILE: /run/secrets/resend_api_key
    secrets:
      - stripe_secret_key
      - resend_api_key
      - auth_secret
    networks:
      - backend
      - frontend
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`api.yourdomain.com`)"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
        - "traefik.http.services.backend.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health')"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

  # Frontend App
  frontend:
    image: ghcr.io/YOUR_ORG/zillow-agent-lead-gen-app/frontend:latest
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE: https://api.yourdomain.com/api
    networks:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`yourdomain.com`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
        - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/')"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

  # Background Workers
  worker:
    image: ghcr.io/YOUR_ORG/zillow-agent-lead-gen-app/backend:latest
    command: ["node", "dist/jobs/workers.js"]
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:password@postgres:5432/zillow_nz
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ENABLE_BACKGROUND_JOBS: "true"
      STRIPE_SECRET_KEY_FILE: /run/secrets/stripe_secret_key
      RESEND_API_KEY_FILE: /run/secrets/resend_api_key
    secrets:
      - stripe_secret_key
      - resend_api_key
    networks:
      - backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # Traefik Reverse Proxy (optional)
  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@yourdomain.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_certs:/letsencrypt
    networks:
      - frontend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`traefik.yourdomain.com`)"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"

networks:
  frontend:
    driver: overlay
    attachable: true
  backend:
    driver: overlay
    internal: true

volumes:
  postgres_data:
  redis_data:
  traefik_certs:

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  stripe_secret_key:
    external: true
  resend_api_key:
    external: true
  auth_secret:
    external: true
